# App
name = "ImClip"
comment = "ImClip is a Dear ImGui clipboard manager application"
version = "0.1.0"
website = "https://github.com/Patitotective/ImClip"
authors = ["Patitotective <https://github.com/Patitotective>"]
categories = ["Utility"]

# AppImage
ghRepo = "Patitotective/ImClip"

stylePath = "assets/style.toml"
iconPath = "assets/icon.png"
svgIconPath = "assets/icon.svg"
iconFontPath = "assets/forkawesome-webfont.ttf"
fontPath = "assets/ProggyVector Regular.ttf" # Other options are Roboto-Regular.ttf, Cousine-Regular.ttf or Karla-Regular.ttf
fontSize = 16.0

# Window
minSize = [200, 200] # Width, height

# Settings for the preferences window
[settings.maxBuffer]
display = "Max buffer"
type = "slider"
default = 100
min = 10
max = 1000
format = "%d"
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiSliderFlags
